return {
  ["1"] = { id = "1", name = "Basic Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["2"] = { id = "2", name = "Donut Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 4, multiplier = 2, isMultiplicative = false, specialEffects = {} },
  ["3"] = { id = "3", name = "Basic Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["4"] = { id = "4", name = "Stone Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["5"] = { id = "5", name = "Duality Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["6"] = { id = "6", name = "Basic Walled Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["7"] = { id = "7", name = "Half Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["8"] = { id = "8", name = "Mini Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["9"] = { id = "9", name = "Large Conveyor Ramp", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["10"] = { id = "10", name = "Conveyor Ramp", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["11"] = { id = "11", name = "Ore Wash", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 1.25, isMultiplicative = true, specialEffects = { "Extinguishing Cleanse" } },
  ["12"] = { id = "12", name = "Heligrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["13"] = { id = "13", name = "Jellyfish Jam", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "PB&J Time!" } },
  ["14"] = { id = "14", name = "Directional Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Directional" } },
  ["15"] = { id = "15", name = "Ore Gate", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Gate" } },
  ["16"] = { id = "16", name = "Applesauce Jam", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.05, isMultiplicative = true, specialEffects = { "PB&J Time!" } },
  ["17"] = { id = "17", name = "Peanutbutter Bop", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["18"] = { id = "18", name = "Chocobutter Bop", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.05, isMultiplicative = true, specialEffects = {} },
  ["19"] = { id = "19", name = "Portable Flamethrower", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 1.5, isMultiplicative = true, specialEffects = { "Fire" } },
  ["20"] = { id = "20", name = "Solar Supercharger", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["21"] = { id = "21", name = "Extraterrestrial Incubator", isRangeUpgrader = true, minimumValue = 0, useLimit = 1000, multiplier = 1.09, isMultiplicative = true, specialEffects = {} },
  ["22"] = { id = "22", name = "B.B Radiator", isRangeUpgrader = false, minimumValue = nil, useLimit = 4, multiplier = 1.5, isMultiplicative = true, specialEffects = {} },
  ["23"] = { id = "23", name = "Sapphire Supercharger", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 1.8, isMultiplicative = true, specialEffects = {} },
  ["24"] = { id = "24", name = "Ruby Refiner", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["25"] = { id = "25", name = "Aerogel Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 1.65, isMultiplicative = true, specialEffects = {} },
  ["26"] = { id = "26", name = "Sky-High Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 4, multiplier = 1.4, isMultiplicative = true, specialEffects = {} },
  ["27"] = { id = "27", name = "Dual-Portable Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 16, multiplier = 1.07, isMultiplicative = true, specialEffects = {} },
  ["28"] = { id = "28", name = "Iron Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["29"] = { id = "29", name = "Copper Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["30"] = { id = "30", name = "Silver Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["31"] = { id = "31", name = "Gold Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["32"] = { id = "32", name = "Centering Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["33"] = { id = "33", name = "Conveyor Wall (Narrow)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["34"] = { id = "34", name = "Conveyor Wall (Wide)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["35"] = { id = "35", name = "Raised Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["36"] = { id = "36", name = "Soaring Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["37"] = { id = "37", name = "Value Filter (Right)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Ore Filter" } },
  ["38"] = { id = "38", name = "Value Filter (Left)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Ore Filter" } },
  ["39"] = { id = "39", name = "Raised-To-Soaring Ramp", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["40"] = { id = "40", name = "Deltatime Dunes", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Shifted Upgrade" } },
  ["41"] = { id = "41", name = "Timefreeze Dunes", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Shifted Upgrade" } },
  ["42"] = { id = "42", name = "Toxic Money", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4, isMultiplicative = true, specialEffects = { "Toxic Injection" } },
  ["43"] = { id = "43", name = "Venomous Money", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.4, isMultiplicative = true, specialEffects = { "Toxic Injection" } },
  ["44"] = { id = "44", name = "Dreamscape", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4, isMultiplicative = true, specialEffects = {} },
  ["45"] = { id = "45", name = "Nightmarescape", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.4, isMultiplicative = true, specialEffects = {} },
  ["46"] = { id = "46", name = "Cheesy Moonscape", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Louie's Misery", "Ultra Cheezy" } },
  ["47"] = { id = "47", name = "Astral Moonscape", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.05, isMultiplicative = true, specialEffects = { "Louie's Misery", "Ultra Cheezy" } },
  ["48"] = { id = "48", name = "Pancakifier", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.25, isMultiplicative = true, specialEffects = { "Pan Press" } },
  ["49"] = { id = "49", name = "P.A.N.C.A.K.E", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.74, isMultiplicative = true, specialEffects = { "Pan Press" } },
  ["50"] = { id = "50", name = "The Oxymoron", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2, isMultiplicative = true, specialEffects = { "Mindlessly Intelligent", "Savantly Foolish" } },
  ["51"] = { id = "51", name = "Flash of Genius", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2.7, isMultiplicative = true, specialEffects = { "Mindlessly Intelligent", "Savantly Foolish" } },
  ["52"] = { id = "52", name = "Cardboard Castle", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 1.5, isMultiplicative = true, specialEffects = {} },
  ["53"] = { id = "53", name = "Cosmite Toilet", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["54"] = { id = "54", name = "Green Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ¸ <font color=\"rgb(58, 255, 120)\">Green</font> Receiver" } },
  ["55"] = { id = "55", name = "Green Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ¸ <font color=\"rgb(58, 255, 120)\">Green</font> Sender" } },
  ["56"] = { id = "56", name = "Blue Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ’§ <font color=\"rgb(57, 238, 255)\">Blue</font> Receiver" } },
  ["57"] = { id = "57", name = "Blue Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ’§ <font color=\"rgb(57, 238, 255)\">Blue</font> Sender" } },
  ["58"] = { id = "58", name = "Yellow Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸŒ©ï¸ <font color=\"rgb(255, 221, 57)\">Yellow</font> Receiver" } },
  ["59"] = { id = "59", name = "Yellow Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸŒ©ï¸ <font color=\"rgb(255, 221, 57)\">Yellow</font> Sender" } },
  ["60"] = { id = "60", name = "Purple Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸŒ™ <font color=\"rgb(213, 57, 255)\">Purple</font> Receiver" } },
  ["61"] = { id = "61", name = "Purple Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸŒ™ <font color=\"rgb(213, 57, 255)\">Purple</font> Sender" } },
  ["62"] = { id = "62", name = "Red Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ’¢ <font color=\"rgb(255, 57, 89)\">Red</font> Receiver" } },
  ["63"] = { id = "63", name = "Red Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ’¢ <font color=\"rgb(255, 57, 89)\">Red</font> Sender" } },
  ["64"] = { id = "64", name = "Orange Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ’¥ <font color=\"rgb(255, 145, 57)\">Orange</font> Receiver" } },
  ["65"] = { id = "65", name = "Orange Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "ðŸ’¥ <font color=\"rgb(255, 145, 57)\">Orange</font> Sender" } },
  ["66"] = { id = "66", name = "Conveyor Converter (Right)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["67"] = { id = "67", name = "Conveyor Converter (Left)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["68"] = { id = "68", name = "Advanced Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["69"] = { id = "69", name = "Moon Base Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 8, isMultiplicative = true, specialEffects = {} },
  ["70"] = { id = "70", name = "Fishy Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["71"] = { id = "71", name = "Nuclear Silo Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 12, isMultiplicative = true, specialEffects = {} },
  ["72"] = { id = "72", name = "Advanced Refiner", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 5, isMultiplicative = false, specialEffects = {} },
  ["73"] = { id = "73", name = "Stardust Infuser", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["74"] = { id = "74", name = "Hologram Projector", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["75"] = { id = "75", name = "Raised Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 5, isMultiplicative = true, specialEffects = {} },
  ["76"] = { id = "76", name = "Right Turn Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 1.15, isMultiplicative = true, specialEffects = {} },
  ["77"] = { id = "77", name = "Left Turn Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 1.15, isMultiplicative = true, specialEffects = {} },
  ["78"] = { id = "78", name = "Portable Shortbeam Projector", isRangeUpgrader = false, minimumValue = nil, useLimit = 16, multiplier = 1.1, isMultiplicative = true, specialEffects = {} },
  ["79"] = { id = "79", name = "Triangular Upgrader", isRangeUpgrader = true, minimumValue = 1000, useLimit = 5000, multiplier = 1.07, isMultiplicative = true, specialEffects = {} },
  ["80"] = { id = "80", name = "Sparkling Clean", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 1.5, isMultiplicative = true, specialEffects = { "Cleanse" } },
  ["81"] = { id = "81", name = "Sparkling Clean Ultra Lemon Orewashing Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.03, isMultiplicative = true, specialEffects = { "Sparkling Clean Ultra Lemon Orewashing Cleanse" } },
  ["82"] = { id = "82", name = "Golden Orchard", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 25, isMultiplicative = true, specialEffects = {} },
  ["83"] = { id = "83", name = "Diamond Orchard", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 33.8, isMultiplicative = true, specialEffects = {} },
  ["84"] = { id = "84", name = "Ant-Antennae Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 6, multiplier = 1.3, isMultiplicative = true, specialEffects = {} },
  ["85"] = { id = "85", name = "Caterpillar Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 1.5, isMultiplicative = true, specialEffects = {} },
  ["86"] = { id = "86", name = "Tall Conveyor Wall (Wide)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["87"] = { id = "87", name = "Tag Scanner", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["88"] = { id = "88", name = "Soaring Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 6.5, isMultiplicative = true, specialEffects = {} },
  ["89"] = { id = "89", name = "Orescilloscope", isRangeUpgrader = true, minimumValue = 5000, useLimit = 20000, multiplier = 1.43, isMultiplicative = true, specialEffects = {} },
  ["90"] = { id = "90", name = "Orbgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 8, multiplier = 1.35, isMultiplicative = true, specialEffects = {} },
  ["91"] = { id = "91", name = "Grandfather Clock", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Time Reaction" } },
  ["92"] = { id = "92", name = "Satellitegrader", isRangeUpgrader = true, minimumValue = 20000, useLimit = 160000, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["93"] = { id = "93", name = "Platinum Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["94"] = { id = "94", name = "Rhodium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["95"] = { id = "95", name = "Diamond Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["96"] = { id = "96", name = "Button-Powered Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Button" } },
  ["97"] = { id = "97", name = "Corner Conveyor Wall (Inner)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["98"] = { id = "98", name = "Corner Conveyor Wall (Outer)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["99"] = { id = "99", name = "Tall Conveyor Wall (Narrow)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["100"] = { id = "100", name = "Tall Corner Conveyor Wall (Inner)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["101"] = { id = "101", name = "Tall Corner Conveyor Wall (Outer)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["102"] = { id = "102", name = "Persisting Capacitor", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 2.25, isMultiplicative = true, specialEffects = {} },
  ["103"] = { id = "103", name = "Anatomically Accurate Brain", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["104"] = { id = "104", name = "Shiverpeak Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 15, isMultiplicative = true, specialEffects = { "Burning Recollection" } },
  ["105"] = { id = "105", name = "Nuclearpeak Processor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 20.3, isMultiplicative = true, specialEffects = { "Burning Recollection" } },
  ["106"] = { id = "106", name = "Wormhole Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 3, isMultiplicative = true, specialEffects = { "Sender" } },
  ["107"] = { id = "107", name = "Wormhole Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = { "Receiver" } },
  ["108"] = { id = "108", name = "Precursor Teleporter (Sender)", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 4.05, isMultiplicative = true, specialEffects = { "Sender" } },
  ["109"] = { id = "109", name = "Precursor Teleporter (Receiver)", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.7, isMultiplicative = true, specialEffects = { "Receiver" } },
  ["110"] = { id = "110", name = "Gumball Enhancer", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["111"] = { id = "111", name = "Luminium Pillar", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 12.5, isMultiplicative = true, specialEffects = { "Base Upgrade" } },
  ["112"] = { id = "112", name = "Celestial Pillar", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 16.9, isMultiplicative = true, specialEffects = { "Base Upgrade" } },
  ["113"] = { id = "113", name = "Golden Goose", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.5, isMultiplicative = true, specialEffects = {} },
  ["114"] = { id = "114", name = "Rosegold Goose", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3.38, isMultiplicative = true, specialEffects = {} },
  ["115"] = { id = "115", name = "Fresh Out of the Oven", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.25, isMultiplicative = true, specialEffects = {} },
  ["116"] = { id = "116", name = "Shadowflame Pedestal", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["117"] = { id = "117", name = "Shadowflame", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = { "Shadowflame" } },
  ["118"] = { id = "118", name = "Tip Jar :)", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = { "Robux Scaling" } },
  ["121"] = { id = "121", name = "Prismite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["122"] = { id = "122", name = "Monochromatic Prismite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["123"] = { id = "123", name = "Mushite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Poison Growth", "Poison Resistance" } },
  ["124"] = { id = "124", name = "Enchanted Mushite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Poison Growth", "Poison Resistance" } },
  ["125"] = { id = "125", name = "Deepspace Geometrica", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4, isMultiplicative = true, specialEffects = {} },
  ["126"] = { id = "126", name = "Deepspace Monochromatica", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.4, isMultiplicative = true, specialEffects = {} },
  ["127"] = { id = "127", name = "Autumn's Magic", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 8, isMultiplicative = true, specialEffects = {} },
  ["128"] = { id = "128", name = "Bronze Reincarnations Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["129"] = { id = "129", name = "Silver Reincarnations Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["130"] = { id = "130", name = "Gold Reincarnations Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["131"] = { id = "131", name = "Bronze Playtime Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["132"] = { id = "132", name = "Silver Playtime Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["133"] = { id = "133", name = "Gold Playtime Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["134"] = { id = "134", name = "Bronze Money Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["135"] = { id = "135", name = "Silver Money Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["136"] = { id = "136", name = "Gold Money Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["137"] = { id = "137", name = "Bronze Donations Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["138"] = { id = "138", name = "Silver Donations Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["139"] = { id = "139", name = "Gold Donations Trophy", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["140"] = { id = "140", name = "Nostalgia Bait", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["141"] = { id = "141", name = "Vintage Bait", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2.7, isMultiplicative = true, specialEffects = {} },
  ["142"] = { id = "142", name = "The Pointer", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Initial Velocity" } },
  ["143"] = { id = "143", name = "Giant Acorn", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["144"] = { id = "144", name = "Pumpkinium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["145"] = { id = "145", name = "Luminium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Luminium" } },
  ["146"] = { id = "146", name = "Celestial Luminium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Luminium" } },
  ["147"] = { id = "147", name = "Chaotic Residue", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["148"] = { id = "148", name = "Royal Flush", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["149"] = { id = "149", name = "Divine Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["150"] = { id = "150", name = "Luck Manipulator", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 10, isMultiplicative = true, specialEffects = { "Luck's Manipulation" } },
  ["151"] = { id = "151", name = "Forsaken Companion", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.5, isMultiplicative = true, specialEffects = {} },
  ["152"] = { id = "152", name = "Potted Tree", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["153"] = { id = "153", name = "Potted Palm Tree", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["154"] = { id = "154", name = "Lamp Post", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["155"] = { id = "155", name = "Big Rock", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["156"] = { id = "156", name = "Spooky Smores", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4, isMultiplicative = true, specialEffects = { "Fire" } },
  ["157"] = { id = "157", name = "Fungal Pillar", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Poison" } },
  ["158"] = { id = "158", name = "Spookypop", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 1.5, isMultiplicative = true, specialEffects = {} },
  ["159"] = { id = "159", name = "Pumpkin Patch", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.5, isMultiplicative = true, specialEffects = {} },
  ["160"] = { id = "160", name = "Manor Mimic", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 7, isMultiplicative = true, specialEffects = {} },
  ["161"] = { id = "161", name = "Corrupt Manor", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 9.45, isMultiplicative = true, specialEffects = {} },
  ["162"] = { id = "162", name = "Divine Delicacy", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["163"] = { id = "163", name = "VIP Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["164"] = { id = "164", name = "Deathday Cake", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Hungry Pyre" } },
  ["165"] = { id = "165", name = "Crate Drizzle", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["166"] = { id = "166", name = "Nature's Grasp", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["167"] = { id = "167", name = "Giant Diamond Mine", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["168"] = { id = "168", name = "Porcelain Doomsday Event", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5, isMultiplicative = true, specialEffects = { "Contagious Brainrot", "Laser Burns" } },
  ["169"] = { id = "169", name = "Infernal Doomsday Event", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6.75, isMultiplicative = true, specialEffects = { "Contagious Brainrot", "Laser Burns" } },
  ["170"] = { id = "170", name = "Boostgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["171"] = { id = "171", name = "Squidsea Symphony", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Inspiring Notes" } },
  ["172"] = { id = "172", name = "Silent Symphony", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.05, isMultiplicative = true, specialEffects = { "Inspiring Notes" } },
  ["173"] = { id = "173", name = "Solar Flare", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = { "Horizon's Reach", "Horizon's Touch" } },
  ["174"] = { id = "174", name = "Black Hole Sun", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.7, isMultiplicative = true, specialEffects = { "Horizon's Touch", "Horizon's Reach" } },
  ["175"] = { id = "175", name = "Plasmagrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Plasma Conversion" } },
  ["176"] = { id = "176", name = "Ball Lightning", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Plasma Conversion" } },
  ["177"] = { id = "177", name = "Whimsical Windmill", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 30, isMultiplicative = true, specialEffects = { "Wind Power!" } },
  ["178"] = { id = "178", name = "Cherry Windmill", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 40.5, isMultiplicative = true, specialEffects = { "Wind Power!" } },
  ["179"] = { id = "179", name = "Dream Eater", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 20, isMultiplicative = true, specialEffects = { "Dream Sucker" } },
  ["180"] = { id = "180", name = "Cotton Candy Eater", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 27, isMultiplicative = true, specialEffects = { "Dream Sucker" } },
  ["181"] = { id = "181", name = "MinersHavenFan2015", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = { "Casey's Evaluation" } },
  ["182"] = { id = "182", name = "â­ BurnItNow MinersHavenFan2015 â­", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.7, isMultiplicative = true, specialEffects = { "Casey's Evaluation" } },
  ["183"] = { id = "183", name = "Blacksmith Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.25, isMultiplicative = true, specialEffects = { "F'ore'ge" } },
  ["184"] = { id = "184", name = "Thronium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Purifier", "Purity Affinity" } },
  ["185"] = { id = "185", name = "Dark Thronium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Purity Affinity", "Purifier" } },
  ["189"] = { id = "189", name = "Basic Pillar", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["190"] = { id = "190", name = "Apiary Junction", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6, isMultiplicative = true, specialEffects = {} },
  ["191"] = { id = "191", name = "Insufferable Junction", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 8.1, isMultiplicative = true, specialEffects = {} },
  ["192"] = { id = "192", name = "Gamma-Ray Burst", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["193"] = { id = "193", name = "Supernova Burst", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.7, isMultiplicative = true, specialEffects = {} },
  ["194"] = { id = "194", name = "Skybound Spires", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5, isMultiplicative = true, specialEffects = {} },
  ["195"] = { id = "195", name = "Stormy Spires", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6.75, isMultiplicative = true, specialEffects = {} },
  ["196"] = { id = "196", name = "Kitty-Cat Outpawst", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["197"] = { id = "197", name = "Digital Outpawst", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 4.05, isMultiplicative = true, specialEffects = {} },
  ["198"] = { id = "198", name = "Toilet Trove", isRangeUpgrader = true, minimumValue = 0, useLimit = 250000, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["199"] = { id = "199", name = "Toxic Trove", isRangeUpgrader = true, minimumValue = 0, useLimit = 337500, multiplier = 4.05, isMultiplicative = true, specialEffects = {} },
  ["200"] = { id = "200", name = "Winner Winner Turkey Dinner", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["201"] = { id = "201", name = "Cocoa Laser", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Fire" } },
  ["202"] = { id = "202", name = "True Tycoonist", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.5, isMultiplicative = true, specialEffects = {} },
  ["203"] = { id = "203", name = "Grand Feast", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 8, isMultiplicative = true, specialEffects = {} },
  ["204"] = { id = "204", name = "Karmite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Gold Award" } },
  ["205"] = { id = "205", name = "The Crate System", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["206"] = { id = "206", name = "Undead Uprising", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4, isMultiplicative = true, specialEffects = { "Transparency" } },
  ["207"] = { id = "207", name = "Devilish Uprising", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.4, isMultiplicative = true, specialEffects = { "Transparency" } },
  ["208"] = { id = "208", name = "Time Capsule", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Item Age Reaction" } },
  ["209"] = { id = "209", name = "WEEWOO Capsule", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.05, isMultiplicative = true, specialEffects = { "Item Age Reaction" } },
  ["210"] = { id = "210", name = "The Grand Tree", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 22, isMultiplicative = true, specialEffects = {} },
  ["211"] = { id = "211", name = "Testament of Skill", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.4, isMultiplicative = true, specialEffects = {} },
  ["212"] = { id = "212", name = "Jolly The Snowman", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3.5, isMultiplicative = true, specialEffects = {} },
  ["213"] = { id = "213", name = "Dynamic Dubstep", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5, isMultiplicative = true, specialEffects = {} },
  ["214"] = { id = "214", name = "Sunset Song", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6.75, isMultiplicative = true, specialEffects = {} },
  ["215"] = { id = "215", name = "Nostalgic Rollercoaster", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 4.5, isMultiplicative = true, specialEffects = {} },
  ["216"] = { id = "216", name = "Vintage Rollercoaster", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 6.75, isMultiplicative = true, specialEffects = {} },
  ["217"] = { id = "217", name = "Kitty-Cat Furtress", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 5.25, isMultiplicative = true, specialEffects = {} },
  ["218"] = { id = "218", name = "Digital Furtress", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 7.88, isMultiplicative = true, specialEffects = {} },
  ["219"] = { id = "219", name = "Deltatime Capsule", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.5, isMultiplicative = true, specialEffects = { "Periodic Prison", "Temporal Infusion" } },
  ["220"] = { id = "220", name = "Timefreeze Capsule", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3.75, isMultiplicative = true, specialEffects = { "Periodic Prison", "Temporal Infusion" } },
  ["221"] = { id = "221", name = "JUNE 12 2015 THE PORCELAIN DOOMSDAY OF THE  HAVEN", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6.5, isMultiplicative = true, specialEffects = { "Laser Burns", "Casey's Evaluation", "Contagious Brainrot" } },
  ["222"] = { id = "222", name = "â­ BURNT JUNE 12 2015 THE PORCELAIN DOOMSDAY OF THE  HAVEN â­", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 9.75, isMultiplicative = true, specialEffects = { "Laser Burns", "Casey's Evaluation", "Contagious Brainrot" } },
  ["223"] = { id = "223", name = "Easier Times", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3.5, isMultiplicative = true, specialEffects = {} },
  ["224"] = { id = "224", name = "Toy Express", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.5, isMultiplicative = true, specialEffects = {} },
  ["225"] = { id = "225", name = "Alluring Glow", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["226"] = { id = "226", name = "Work In Progress", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2, isMultiplicative = true, specialEffects = { "Item Age Reaction" } },
  ["227"] = { id = "227", name = "Forklift", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["228"] = { id = "228", name = "Traffic Cone", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["229"] = { id = "229", name = "Stud Conveyor", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["230"] = { id = "230", name = "Rubber Tyrant", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["231"] = { id = "231", name = "Late Frights", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6.25, isMultiplicative = true, specialEffects = {} },
  ["232"] = { id = "232", name = "Late Delights", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["233"] = { id = "233", name = "New Year's Rave", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 8.26, isMultiplicative = true, specialEffects = {} },
  ["234"] = { id = "234", name = "Doomsday Watch", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 10, isMultiplicative = true, specialEffects = { "Apocalypse Power", "Impend" } },
  ["235"] = { id = "235", name = "Inverted Watch", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 15, isMultiplicative = true, specialEffects = { "Apocalypse Power", "Impend" } },
  ["236"] = { id = "236", name = "Divine Protection", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 30, isMultiplicative = true, specialEffects = { "Divine Blessings", "Providence" } },
  ["237"] = { id = "237", name = "Astral Protection", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 45, isMultiplicative = true, specialEffects = { "Divine Blessings", "Providence" } },
  ["238"] = { id = "238", name = "Bliss State", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 50, isMultiplicative = true, specialEffects = { "Experience Transfer", "Life Flashing Bef-Ore y-Ore eyes" } },
  ["239"] = { id = "239", name = "Oblivion State", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 75, isMultiplicative = true, specialEffects = { "Experience Transfer", "Life Flashing Bef-Ore y-Ore eyes" } },
  ["240"] = { id = "240", name = "Hatsplosion Rain", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5, isMultiplicative = true, specialEffects = {} },
  ["241"] = { id = "241", name = "Duck Rain", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6.75, isMultiplicative = true, specialEffects = {} },
  ["242"] = { id = "242", name = "Seraphium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Angelifier", "Angelic Affinity" } },
  ["243"] = { id = "243", name = "Dark Seraphium Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Angelic Affinity", "Angelifier" } },
  ["244"] = { id = "244", name = "EDModulation", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 8, isMultiplicative = true, specialEffects = {} },
  ["245"] = { id = "245", name = "Sunset Modulation", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 12, isMultiplicative = true, specialEffects = {} },
  ["246"] = { id = "246", name = "Kittyraver", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 6.5, isMultiplicative = true, specialEffects = {} },
  ["247"] = { id = "247", name = "Sunsetkittyraver", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 9.75, isMultiplicative = true, specialEffects = {} },
  ["248"] = { id = "248", name = "Netfisher", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4, isMultiplicative = true, specialEffects = {} },
  ["249"] = { id = "249", name = "Netfisher But It Looks Cooler", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.4, isMultiplicative = true, specialEffects = {} },
  ["250"] = { id = "250", name = "Sparkling Trove", isRangeUpgrader = true, minimumValue = 0, useLimit = 3000000, multiplier = 3, isMultiplicative = true, specialEffects = { "Cleanse" } },
  ["251"] = { id = "251", name = "Sparkling Trove Ultra Toxic Orewashing Upgrader", isRangeUpgrader = true, minimumValue = 0, useLimit = 4500000, multiplier = 4.5, isMultiplicative = true, specialEffects = { "Cleanse" } },
  ["252"] = { id = "252", name = "Flower of Life", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Life Cycle" } },
  ["253"] = { id = "253", name = "Seed of Life", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Life Cycle" } },
  ["256"] = { id = "256", name = "Alpha Plaque", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["257"] = { id = "257", name = "Chronostasis", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Stasis" } },
  ["258"] = { id = "258", name = "Chronoflux", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Stasis" } },
  ["259"] = { id = "259", name = "Monoblast", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5, isMultiplicative = true, specialEffects = { "Monochromo Infusion", "Monochromo Overload!" } },
  ["260"] = { id = "260", name = "Chromablast", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6.75, isMultiplicative = true, specialEffects = { "Monochromo Infusion", "Monochromo Overload!" } },
  ["261"] = { id = "261", name = "Dark Light", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 1.8, isMultiplicative = true, specialEffects = {} },
  ["262"] = { id = "262", name = "Gamma Light", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 2.43, isMultiplicative = true, specialEffects = {} },
  ["263"] = { id = "263", name = "Heartache", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.5, isMultiplicative = true, specialEffects = {} },
  ["264"] = { id = "264", name = "Heartful", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3.38, isMultiplicative = true, specialEffects = {} },
  ["265"] = { id = "265", name = "Heartade", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.5, isMultiplicative = true, specialEffects = {} },
  ["266"] = { id = "266", name = "Heartless", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3.38, isMultiplicative = true, specialEffects = {} },
  ["267"] = { id = "267", name = "Void Star", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 9, isMultiplicative = true, specialEffects = {} },
  ["268"] = { id = "268", name = "Gamma Star", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 13.5, isMultiplicative = true, specialEffects = {} },
  ["269"] = { id = "269", name = "Money Laundering", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Dirty Money", "Clean Slate" } },
  ["270"] = { id = "270", name = "Money Laundering Liquid Lemon Scent 2 L Laundry Detergent", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 4.5, isMultiplicative = true, specialEffects = { "Dirty Money", "Clean Slate" } },
  ["271"] = { id = "271", name = "Gift of Generosity", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = { "Gift Scaling" } },
  ["272"] = { id = "272", name = "Burning Multitasker", isRangeUpgrader = false, minimumValue = nil, useLimit = 8, multiplier = 1.25, isMultiplicative = true, specialEffects = {} },
  ["275"] = { id = "275", name = "Heartbreak Cake", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 7.25, isMultiplicative = true, specialEffects = {} },
  ["276"] = { id = "276", name = "Hand of God", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 20, isMultiplicative = true, specialEffects = { "Tag Count Reaction" } },
  ["277"] = { id = "277", name = "Heaven's Hand", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 27, isMultiplicative = true, specialEffects = { "Tag Count Reaction" } },
  ["278"] = { id = "278", name = "Blank Canvas", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 2.75, isMultiplicative = true, specialEffects = { "Artistic Inspiration" } },
  ["279"] = { id = "279", name = "Lifeless Piece", isRangeUpgrader = false, minimumValue = nil, useLimit = 2, multiplier = 3.71, isMultiplicative = true, specialEffects = { "Artistic Inspiration" } },
  ["280"] = { id = "280", name = "Ore's Choice", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 5.5, isMultiplicative = true, specialEffects = { "Patience's Virtue" } },
  ["281"] = { id = "281", name = "Purpled Ore's Choice", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 7.43, isMultiplicative = true, specialEffects = { "Patience's Virtue" } },
  ["282"] = { id = "282", name = "Radium Irradiator", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 2.5, isMultiplicative = true, specialEffects = { "Radical Radium Overload" } },
  ["283"] = { id = "283", name = "Uranium Irradiator", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3.38, isMultiplicative = true, specialEffects = { "Radical Radium Overload" } },
  ["284"] = { id = "284", name = "Letting Go", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 6, isMultiplicative = true, specialEffects = { "Density Change" } },
  ["285"] = { id = "285", name = "Forgotten Memories", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 8.1, isMultiplicative = true, specialEffects = { "Density Change" } },
  ["286"] = { id = "286", name = "Value Scaler", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Value Scanner" } },
  ["287"] = { id = "287", name = "Stellar Rice", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["288"] = { id = "288", name = "Eldritch Rice", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["290"] = { id = "290", name = "The Probe", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 10, isMultiplicative = true, specialEffects = {} },
  ["292"] = { id = "292", name = "Doublegrader", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["293"] = { id = "293", name = "Micrograder", isRangeUpgrader = false, minimumValue = nil, useLimit = 4, multiplier = nil, isMultiplicative = nil, specialEffects = { "Empower" } },
  ["294"] = { id = "294", name = "Watercooler", isRangeUpgrader = false, minimumValue = nil, useLimit = 5, multiplier = nil, isMultiplicative = nil, specialEffects = { "Delayed Multiply", "Cleanse" } },
  ["295"] = { id = "295", name = "Plasma Saucer", isRangeUpgrader = true, minimumValue = 160000, useLimit = 3250000, multiplier = 1.04, isMultiplicative = true, specialEffects = { "Tag Reaction" } },
  ["296"] = { id = "296", name = "Pipeline", isRangeUpgrader = true, minimumValue = 2500000000, useLimit = nil, multiplier = 5, isMultiplicative = true, specialEffects = {} },
  ["297"] = { id = "297", name = "Triplegrader", isRangeUpgrader = true, minimumValue = 3250000, useLimit = 26000000, multiplier = 2, isMultiplicative = true, specialEffects = {} },
  ["298"] = { id = "298", name = "Alloyed Steel Frame", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 1.75, isMultiplicative = true, specialEffects = { "Effect Affinity" } },
  ["299"] = { id = "299", name = "Ore Slide", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = 3, isMultiplicative = true, specialEffects = {} },
  ["300"] = { id = "300", name = "Soaring Triplegrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 3, multiplier = 2.5, isMultiplicative = true, specialEffects = {} },
  ["301"] = { id = "301", name = "Emerald Enricher", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Emeradic Solidifier" } },
  ["302"] = { id = "302", name = "Amethyst Augmentor", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Delayed Multiply" } },
  ["303"] = { id = "303", name = "Refined Refiner", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Sacrifice" } },
  ["304"] = { id = "304", name = "Portable Device", isRangeUpgrader = false, minimumValue = nil, useLimit = 5, multiplier = 1.25, isMultiplicative = true, specialEffects = { "Ramping Multiplier" } },
  ["305"] = { id = "305", name = "Ore Calciner", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 25, isMultiplicative = true, specialEffects = {} },
  ["306"] = { id = "306", name = "Solarite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Effect Affinity", "Fire" } },
  ["307"] = { id = "307", name = "Painite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Fire" } },
  ["308"] = { id = "308", name = "Mechanical Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 1, multiplier = nil, isMultiplicative = nil, specialEffects = { "Tag Count Reaction" } },
  ["309"] = { id = "309", name = "Reactor Core", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 37.5, isMultiplicative = true, specialEffects = {} },
  ["310"] = { id = "310", name = "Black Hole Generator", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 60, isMultiplicative = true, specialEffects = { "Effect Affinity" } },
  ["311"] = { id = "311", name = "X-Raygrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 10, multiplier = 1.2, isMultiplicative = true, specialEffects = {} },
  ["312"] = { id = "312", name = "Molten Upgrader", isRangeUpgrader = false, minimumValue = nil, useLimit = 10, multiplier = 3, isMultiplicative = true, specialEffects = { "Fire" } },
  ["313"] = { id = "313", name = "Galaxite Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = { "Effect Affinity", "Fire" } },
  ["315"] = { id = "315", name = "Toiletageddon", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = 75, isMultiplicative = true, specialEffects = {} },
  ["316"] = { id = "316", name = "Developer Dropper", isRangeUpgrader = false, minimumValue = nil, useLimit = nil, multiplier = nil, isMultiplicative = nil, specialEffects = {} },
  ["317"] = { id = "317", name = "Ultimate Upgrader", isRangeUpgrader = true, minimumValue = 26000000, useLimit = 2500000000, multiplier = 1.1, isMultiplicative = true, specialEffects = {} },
}
